# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2688955096da7879cdd5ec16cc8da8482bae98fd123acb9cc5c49de58e8820e97aa511cc26a17126d68c8cda7d21457104affaacf8bce4f6e3afe5964580db97

test:
  secret_key_base: f58544693e7690a80244574727a477488638aea0668cd95843779d46e8ca38dba09747896c9b4979b423d91042fdef8f22425e8a3d315dfdd1f88c9c9cee9be8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
